config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome', to: 'static_pages#welcome'


  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users, only: [:new, :create, :show]

  #cities
  resources:cities, only: [:show]

  #login/logout
  resources:sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }


  validates :content,
    presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags

  validates :title,
    presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def authenticate_user
    unless current_user
      puts params
      @user = User.new
      render 'sessions/new'
    end

  end
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user

  def show
    @current_city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user
    def index
      @comments = Comment.all
    end  
  
    def show
      @comment = Comment.find(params[:id])
    end  
  
    def new
      
    end  
  
    def create
        @gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.create(content: params[:content], user: User.last, gossip_id: @gossip.id)
  
        if @comment.save
            redirect_to gossip_path(@gossip)
        else
            redirect_to gossip_path(@gossip), alert: "?? ..."
        end
    end
  
    def edit
      @comment = Comment.find(params[:id])
    end
  
    def update
      @gossip = Gossip.find(params[:gossip_id]) 
      @comment = Comment.find(params[:id])
      if @comment.update(content: params[:content])
        redirect_to gossip_path
        flash[:success] = "Comment changed"
      else
        render :edit
        flash[:error] = "Not in valid format!"
  
      end
    end
  
    def destroy
      @comment = Comment.find(params[:id])
        if @comment.destroy
        flash[:success] = "Comment deleted!"
          redirect_to gossip_path(@comment.gossip.id)
        else
          render 'edit'
      end
    end  
  
    #private
  
    def comment_params
        params.require(:comment).permit(:content)
    end
  end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, except: [:index]
  # View a list of gossips
  def index
    @gossips = Gossip.all

    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comments = @gossip.comments
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @gossip = Gossip.new(title: "", content: "", user: User.last)
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

def create
    @gossip = Gossip.new(user: User.last, title: params[:title], content: params[:content])

    if @gossip.save      
      redirect_to "/"
      flash[:success] = "Gossip created!"
    else
      flash[:error] = "Not in valid format! "
      render :new
      
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])

    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition

  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(user: User.last, title: params[:title], content: params[:content])
      redirect_to "/"
      flash[:success] = "Gossip edited!"
    else
      flash[:error] = "Not in valid format!"
      render :edit
    end
  end

  def destroy
    Gossip.find(params[:id]).delete
    redirect_to gossips_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to '/'
    end
     @user = User.new  
  end

  def create
    if current_user
      redirect_to '/'
    end
    @user = User.find_by(email: params[:email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if @user && @user.authenticate(params[:password])
      log_in(@user)
      render 'gossips/index'
    else
      @user = User.new    
      render 'sessions/new'
    end    
  end

  def destroy
    session.delete(:user_id)   
    redirect_to :root 
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def team
  end

  def contact
  end

  def welcome

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    if current_user
      redirect_to '/'
    end
    @user = User.new
    @age = [4..176]  #@age = [7..77] 
  end

  def create
    if current_user
      redirect_to '/'
    end
    
    @city = City.find_by(name: params[:city])

    if @city == nil
      @city = City.create(name: params[:city])
    end

    @user = User.new(
      first_name: params[:first_name], 
      last_name: params[:last_name], 
      description: params[:description],
      email: params[:email],
      password: params[:password], 
      password_confirmation: params[:passwordconfirm],
      age: params[:age],
      city_id: @city.id
    )

    if @user.save
      log_in(@user)
      render 'gossips/index'
    else
      render :new
    end
  end

  def show
    @current_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<br><br>
  <h3><strong><%= @current_city.name %></strong></h3>

<main class="container">
  <h4>Town gossips</h4>
  <br>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.each do |gossip| %>
      <% if gossip.user.city_id == @current_city.id %>
        <div class="card card-body text-center bg-light my-6 mx-6" style="max-width: 18rem;"> 
          <div class="card-body">
            <h5 class="card-title"><%= gossip.user.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>
          </div>
          <div class="card-body">
            <%= link_to "👁", gossip_path(gossip.id), class:"btn btn-light" %>
            <% if current_user%>
              <% if current_user.id == gossip.user_id%>
                <%= link_to "", user_path(current_user.id) %>
              <% end %>
            <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</main>

app/views/comments/_index.html.erb
<div><% @comments.sort_by(&:created_at).each do |comment| %>
  <div class="card bg-light text-right my-2">
    <div class="card-header ">
      <p ><%= comment.content %></p>
      <footer class="blockquote-footer">
        <strong><%= link_to "#{comment.user.first_name + " " + comment.user.last_name}", user_path(comment.user.id) %></strong>
          <cite title="Source Title">
            <% if current_user.id == comment.user_id%>
              <%= link_to "Edit", edit_gossip_comment_path(@gossip.id, comment.id), class:"badge badge-success" %>
              <%= link_to "Supprimer", gossip_comment_path(@gossip.id, comment.id), class:"badge badge-danger", data:{confirm:"Are you sure you want to delete it?", method:"DELETE"} %>
            <% end %>
          </cite>
      </footer>
    </div>
  </div>
<% end %></div>

app/views/comments/_new.html.erb
<div class="container mt-5 form-group">
 <%= form_tag gossip_comments_path(@gossip), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="d-flex flex-row justify-content-center">

      <%= text_field_tag 'content', @comment.content, class:"form-control mx-2", placeholder:"What have you got to say" %>

      <%= submit_tag "Comment!", class:"btn btn-light"%>
      </div>
    <% end %>
</div>

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
      <p class="alert alert-danger d-flex justify-content-center" role="alert"><%= message %></p>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <strong><%= label_tag 'Comment content' %></strong>
      <%= text_area_tag 'content', @comment.content, class:"form-control" %>
      <br />

      <div class="d-flex justify-content-center"><%= submit_tag "Edit comment", class:"btn btn-light btn-lg"%></div>

    <% end %>
        <hr>
    <div style="margin-top: 10px;" class="d-flex justify-content-center"><%= link_to "Home", root_path, :class => "btn  btn-secondary btn-sm" %></div>
</div>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<html>
  <head>
    <title>TheGossiProject</title>
  </head>
  <body>
    <div class="container text-center mt-5">
      <h3 style="color: #053557">Edit Gossip !</h3>
      <div class="m-5">
        <%= form_tag url_for(action: 'update'), method: "put" do %>

          <%= label_tag 'Title' %> <br/>
          <%= text_field_tag 'title' %>
          <br /> <br />

          <%= label_tag 'Content' %> <br/>
          <%= text_area_tag 'content' %>
          <br /> <br />

          <%= submit_tag "Edit" %> 
        <% end %>
        
    </div>
  </body>
</html>

app/views/gossips/index.html.erb
<!doctype html>
<html lang="en">

  <body>
  <% if !flash[:success].nil? %>
    <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
  <% end %>
  <% if !flash[:update].nil? %>
    <div class="alert alert-success" role="alert"><%= flash[:update] %></div>
  <% end %>
  <div>
  <%if session[:user_id] != nil%>
    <br><br><br><br><h3><strong>Hey <%= current_user.first_name %>!</strong></h3>
  <%else %>
    <%if params[:first_name] == nil%>
    
     <br> <br><br><br><h3><strong>Welcome !</strong></h3>
    <%elsif params[:action] == "create" && params[:commit] == "S'inscrire"%>
      <h1>Welcome on our gossip website, <%= params[:first_name] %></h1>
    <%else %>
      <h1>Welcome <%= params[:first_name] %></h1>
  <% end %>
  <% end %>
  </div>
  
  <main class="container">

  <h2><button type="button" class="btn btn-light btn-lg"><%= link_to "New gossip", new_gossip_path %> </button></h2>

<div class="container-fluid">
  <div class="pt-1 my-5 text-center">
    
  </div>
  <div class="row">
    <% Gossip.all.each do |gossip| %>
      <div class="col-l-1 col-md-12 col-sm-6">
        <div class="card border-dark mb-1" style="border-width: 1px;"> 
          <div class="card-body">
            <h5 class="card-title text-center"><%= gossip.title %></h5>
            
            <p class="card-text text-center " > <strong >&quot</strong> <%= link_to gossip.user.first_name, user_path(gossip.user.id) %></p>
          </div>

      
          
         <%= link_to "👁", gossip_path(gossip.id), class:"btn btn-light"%>
        </div>
      </div>
    <% end %>
  </div>
</div>
</main>
  </body>

</html> 

app/views/gossips/new.html.erb
<html>
  <head>
    <title>TheGossiProject</title>
  </head>
  <body>

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
    <% end %>

    <div class="container text-center mt-5">
      <h3 style="color: #053557">New Gossip </h3>
      <div class="m-5">
        <%= form_tag url_for(action: 'create'), method: "post" do %>

          <%= label_tag 'Title' %> <br/>
          <%= text_field_tag 'title' %>
          <br /> <br />

          <%= label_tag 'Content' %> <br/>
          <%= text_area_tag 'content' %>
          <br /> <br />

          <%= submit_tag "Send" %> 
        <% end %>
        
    </div>
  </body>
</html>

app/views/gossips/show.html.erb
<!doctype html>
<html lang="en">

  <body>
  <br><br><br><br>
    <div class="container">
      <h3 class="display-5 text-center text-secondary my-3"><strong>TheGossiProject</strong></h3>

      <div class="row justify-content-center">
          <div class="col-l-1 col-md-8 col-sm-6">
            <div class="card">
              
            <div class="container">
                <div class="card my-5"> 
                 
                  <div class="card-body py-5">
                    <h1 class="card-title text-center">
                      <span class="font-weight-normal"><%= @gossip.title%> 👧⚔️🦇</span>
                      <small><strong >&quot</strong>
                      <a href="<%= user_path(@gossip.user.id) %>" class="text-info"><strong><%= @gossip.user.first_name%><strong> <%= @gossip.user.last_name%></a>
                      </small>
                    </h1>
                    <h4 class="card-text pt-5 px-2"><%= @gossip.content%> 🦉☕</h4>    
                  </div>
                  <div class="card-body text-muted text-right">
                     <%= @gossip.id %>-<%= @gossip.created_at.strftime("%d/%m/%Y") %>
                  </div>
                </div>


              <div class="card-body">
                <h5 class="card-title"><%=@gossip.title %></h5>
                <p class="card-text"><%= @gossip.content %></p>
                <p class="card-text">
                <p class="card-text">
           
                </p>
                <div class="row justify-content-center text-center">
                  <div class="col">
                    <a class='btn btn-link btn-light' href="<%= edit_gossip_path %>">✍️</a>


                  </div>
                  <div class="col">
                    <%= form_tag gossip_path(@gossip.id), method: "delete" do %>
                    <%= submit_tag "🗑️", {class: 'btn btn-link btn-light'} %>
                    <% end %>
                  </div>
                </div>
              </div>
              </div>
            </div>
          </div>
      </div>
          
   <br><br>

<div justify-content-center>
        <% @gossip.comments.each do |comment| %>
          <p> <strong><%= comment.user.first_name %></strong>  </p>
          <p>
            <strong>Comments :</strong>
            <%= comment.content %>
          </p>
          <%= link_to 'Edit',  edit_gossip_comment_path(@gossip)%>
        <% end %>  
      </div>
      <br><br>
      <h2>Comments :</h2>
      <br>
          <div>
            <%= render 'comments/index'%>
            <%= render 'comments/new'%>
          </div>
      </div>
  </body>

</html>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <div class="container alert alert-danger d-flex justify-content-center alert-dismissible fade show" role="alert"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <strong><%= label_tag 'First name' %></strong>
      <%= text_field_tag 'first_name', @user.first_name, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Last name' %></strong>
      <%= text_field_tag 'last_name', @user.last_name, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Description' %></strong>
      <%= text_area_tag 'description', @user.description, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'e-mail' %></strong>
      <%= text_field_tag 'email', @user.email, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Password' %></strong>
      <%= text_field_tag 'password', @user.password, class:"form-control", type:"password", required: true %>
      <br /> 

      <strong><%= label_tag 'Confirme password' %></strong>
      <%= text_field_tag 'passwordconfirm', @user.password_confirmation, class:"form-control", type:"password", required: true %>
      <br /> 

      <strong><%= label_tag 'Age' %>
      <%= text_field_tag 'age', @user.age, class:"form-control", required: true %></strong>
      <br /> 

      <strong><%= label_tag 'City' %>
      <%= text_field_tag 'city', @user.city, class:"form-control", required: true %></strong>
      <br /> 

      <div class="d-flex justify-content-center"><%= submit_tag "S'inscrire", class:"btn btn-success btn-lg"%></strong></div>

    <% end %>
</div>

app/views/users/show.html.erb
<!doctype html>
<html lang="en">

<br><br>
 
  <div class="container">
  <h1 class="display-4 text-center my-5">O<span class="text-primary">0</span><span class="text-danger">@</span><span class="text-warning">@</span >0£µ/£%</h1>

      <div class="row justify-content-center">

        <div class="card flex-row flex-wrap">
         
          <div class="card-block px-2 mt-4 ml-3">
            <h4 class="card-title h2"><%= @current_user.first_name %> <%= @current_user.last_name.upcase %></h4>
            <p class="card-text"><span class="h5"> </span><%= @current_user.age %> ans</p>
            <p class="card-text"><span class="h5"> </span> <a href="<%= city_path(@current_user.city.id) %>"><%= @current_user.city.name %></p></a>

            <p class="card-text"><span class="h5"> </span> <a href="mailto:<%= @current_user.email %>"><%= @current_user.email %></a></p>
            <p class="card-text"><span class="h5"> </span><br /><%= @current_user.description %></p>
            <a href="#" class="btn btn-light">📩</a>
            <div class="w-100"></div>
          </div>
        </div>
      </div>
    </div>
    
  </body>

</html>  