config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome', to: 'static_pages#welcome'


  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users, only: [:new, :create, :show]

  #cities
  resources:cities, only: [:show]

  #login/logout
  resources:sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  validates :title,
    presence: true,
    length: { minimum: 3, maximum: 14 }


  validates :content,
    presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags

  validates :title,
    presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user

  def show
    @current_city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user
    def index
      @comments = Comment.all
    end  
  
    def show
      @comment = Comment.find(params[:id])
    end  
  
    def new
      
    end  
  
    def create
        @gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.create(content: params[:content], user: User.last, gossip_id: @gossip.id)
  
        if @comment.save
            redirect_to gossip_path(@gossip)
        else
            redirect_to gossip_path(@gossip), alert: "?? ..."
        end
    end
  
    def edit
      @comment = Comment.find(params[:id])
    end
  
    def update
      @gossip = Gossip.find(params[:gossip_id]) 
      @comment = Comment.find(params[:id])
      if @comment.update(content: params[:content])
        redirect_to gossip_path
        flash[:success] = "Comment changed"
      else
        render :edit
        flash[:error] = "Not in valid format!"
  
      end
    end
  
    def destroy
      @comment = Comment.find(params[:id])
        if @comment.destroy
        flash[:success] = "Comment deleted!"
          redirect_to gossip_path(@comment.gossip.id)
        else
          render 'edit'
      end
    end  
  
    #private
  
    def comment_params
        params.require(:comment).permit(:content)
    end
  end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, except: [:index]
  # View a list of gossips
  def index
    @gossips = Gossip.all

    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comments = @gossip.comments
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @gossip = Gossip.new(title: "", content: "", user: User.last)
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

def create
    @gossip = Gossip.new(user: User.last, title: params[:title], content: params[:content])

    if @gossip.save      
      redirect_to "/"
      flash[:success] = "Gossip created!"
    else
      flash[:error] = "Not in valid format! "
      render :new
      
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])

    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition

  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(user: User.last, title: params[:title], content: params[:content])
      redirect_to "/"
      flash[:success] = "Gossip edited!"
    else
      flash[:error] = "Not in valid format!"
      render :edit
    end
  end

  def destroy
    Gossip.find(params[:id]).delete
    redirect_to gossips_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    if current_user
      redirect_to '/'
    end
    @user = User.new
    @age = [4..176]  #@age = [7..77] 
  end

  def create
    if current_user
      redirect_to '/'
    end
    
    @city = City.find_by(name: params[:city])

    if @city == nil
      @city = City.create(name: params[:city])
    end

    @user = User.new(
      first_name: params[:first_name], 
      last_name: params[:last_name], 
      description: params[:description],
      email: params[:email],
      password: params[:password], 
      password_confirmation: params[:passwordconfirm],
      age: params[:age],
      city_id: @city.id
    )

    if @user.save
      log_in(@user)
      render 'gossips/index'
    else
      render :new
    end
  end

  def show
    @current_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossiProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- fontawesome CSS -->
    <script src="https://kit.fontawesome.com/ac57f67360.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <% stylesheet_link_tag 'application' %>
    <title>TheGossiProject</title>
  </head>

                   
                      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #87CEEB;">

                       
            <a class="navbar-brand"  <%= link_to "TheGossiProject", root_path %></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" <%= link_to "Home", root_path %><span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" <%= link_to "Team", team_path %></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" <%= link_to "Contact", contact_path %></a>
                  </li>
                  <ul class="navbar-nav">
                  <ul class="navbar-nav">
                  <% if session[:user_id] == nil%>
                    <li class="btn-group">
                      <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Log In / Sign Up
                      </button>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <%= link_to "Sign Up", new_user_path, :class => "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <%= link_to "Log In", new_session_path, :class => "dropdown-item" %>
                      </div>
                    </li>
                  <% else %>
                    <li class="nav-item dropdown">
                      <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%=current_user.first_name + " " + current_user.last_name %>
                      </button>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <%= link_to "Profile", user_path(current_user.id), class: "dropdown-item" %>
                        <!--<%= link_to "Parametres", user_path(current_user.id), class: "dropdown-item" %>-->
                        <div class="dropdown-divider"></div>
                        <%= link_to "Disconnect", session_path(session.id), class:"dropdown-item", method: :delete %>
                      </div>
                    </li>
                  <% end %>
                 </ul>
                </div>
              </div>

              </div>
            </nav>


   
    
    <%= yield %>
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>